# demo_setup.yml

- hosts: localhost
  connection: local
  gather_facts: False

  tasks:

    - name: Provision cluster instances
      ec2:
         key_name: rhel7-1
         group: launch-wizard-1
         instance_type: t2.micro
         image: ami-6f68cf0f
         wait: true
         exact_count: 3
         region: us-west-2
         count_tag:
            Name: ClusterNode
         instance_tags:
            Name: ClusterNode
      register: ec2

    - name: Add all instance public IPs to host group
      add_host: hostname={{ item.public_ip }} groups=ec2hosts
      with_items: "{{ ec2.instances }}"


- hosts: ec2hosts
  name: configuration play
  user: ec2-user
  gather_facts: true

  tasks:

     - name: Check NTP service
       service: name=ntpd state=started
