---
  - name: Add XPRA Repository
    yum_repository:
      name: WinSwitch
      description: WinSwitch Repository
      baseurl: http://winswitch.org/dists/CentOS/$releasever/$basearch/
      gpgkey: https://winswitch.org/gpg.asc
      gpgcheck: yes
    when: ansible_os_family == "RedHat"

  - name: Install XPRA
    yum: name=xpra state=present
    when: ansible_os_family == "RedHat"

  - name: Add to XPRA Group
    user: name=ec2-user groups=xpra append=yes

  - name: Install Xterm
    yum: name=xterm state=present
    when: ansible_os_family == "RedHat"
