---
  - name: Install Metricbeat
    yum: name=https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-5.1.1-x86_64.rpm state=present

  - name: Install Filebeat
    yum: name=https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-5.1.1-x86_64.rpm state=present
