---
- name: Install Docker Repo Package
  yum_repository:
    name: Docker
    description: Docker YUM repo
    baseurl: https://yum.dockerproject.org/repo/main/centos/7/
    gpgcheck: yes
    gpgkey: https://yum.dockerproject.org/gpg

- name: Install Docker
  yum: name=docker-engine state=latest
  tags: docker

- name: Enable Docker
  service: name=docker enabled=yes state=started

- name: User in Docker group
  user: name=ec2-user groups=docker append=yes
  notify:
    - Restart Docker
